# Generated by Django 5.2.11 on 2026-03-03 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCategorySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подписки')),
                ('is_active', models.BooleanField(default=True, help_text='Если снято — пользователь не получает уведомления, но подписка сохраняется', verbose_name='Активна')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='news.category', verbose_name='Категория')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка на категорию',
                'verbose_name_plural': 'Подписки на категории',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='news_userca_user_id_09178a_idx'), models.Index(fields=['category', 'is_active'], name='news_userca_categor_531d43_idx')],
                'unique_together': {('user', 'category')},
            },
        ),
    ]
