"""
Django settings for pr_settings project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from decouple import config
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = config('DEBUG', default=True, cast=bool)

# ALLOWED_HOSTS = []

DEBUG = False
ALLOWED_HOSTS = ['localhost', '127.0.0.1']  # добавить для теста


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.flatpages',
    'django.contrib.humanize',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.yandex',
    'news',
    'accounts',
    'django_filters',
    'django_apscheduler',
    'django_celery_beat',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'pr_settings.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pr_settings.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USERNAME_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.validators.UnicodeUsernameValidator',
    },
]

# ← ← ← И ЭТО (минимальная длина username):
ACCOUNT_USERNAME_MIN_LENGTH = 3

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

LOGIN_URL = '/accounts/login/'

LOGIN_REDIRECT_URL = '/news/'

LOGOUT_REDIRECT_URL = '/news/'

# ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
# ACCOUNT_USERNAME_REQUIRED = True
# ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_LOGIN_METHODS = {'email', 'username'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']
# Кастомная форма регистрации
# ACCOUNT_FORMS = {'signup': 'accounts.forms.CustomSignupForm',}
# ACCOUNT_SIGNUP_FORM_CLASS = 'accounts.forms.CustomSignupForm'
# ACCOUNT_ADAPTER = 'accounts.adapter.CustomAccountAdapter'

# ← Язык (обязательно для русских ошибок):
LANGUAGE_CODE = 'ru'
USE_I18N = True
LOCALE_PATHS = [BASE_DIR / 'locale']

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {'console': {'class': 'logging.StreamHandler'}},
    'root': {'handlers': ['console'], 'level': 'DEBUG'},
    'loggers': {
        'allauth': {'level': 'DEBUG', 'handlers': ['console'], 'propagate': False},
        'allauth.socialaccount': {'level': 'DEBUG', 'handlers': ['console'], 'propagate': False},
    },
}

SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
# Использовать наш адаптер для авто-привязки
SOCIALACCOUNT_ADAPTER = 'accounts.adapter.AutoConnectSocialAccountAdapter'

# =============================================================================
# EMAIL SETTINGS (для рассылок и уведомлений)
# =============================================================================

ADMINS = [
    ('Admin', 'npkap@mail.ru'),  # свой email для теста
]


EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='smtp.yandex.ru')
EMAIL_PORT = config('EMAIL_PORT', default=465, cast=int)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default=EMAIL_HOST_USER)
SERVER_EMAIL = config('SERVER_EMAIL', default=DEFAULT_FROM_EMAIL)
EMAIL_SUBJECT_PREFIX = config('EMAIL_SUBJECT_PREFIX', default='[NewsPortal] ')
EMAIL_TIMEOUT = config('EMAIL_TIMEOUT', default=30, cast=int)


# =============================================================================
# APSCHEDULER SETTINGS
# =============================================================================

APSCHEDULER_DATETIME_FORMAT = "N j, Y, f:s a"
APSCHEDULER_RUN_NOW_TIMEOUT = 25
APSCHEDULER_MAX_EXECUTIONS = 1

SITE_URL = config('SITE_URL', default='http://127.0.0.1:8000')

# =============================================================================
# CELERY CONFIGURATION
# =============================================================================

# URL Redis (локальный по умолчанию)
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'

# Настройки сериализации
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Настройки для периодических задач (beat)
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# Важно для предотвращения зависаний
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 минут

# =============================================================================
# LOGGING CONFIGURATION
# =============================================================================

# Создаём директорию для логов, если её нет
LOG_DIR = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    # Фильтры
    'filters': {
        'debug_only': {
            '()': 'pr_settings.log_filters.DebugFilter',
        },
        'production_only': {
            '()': 'pr_settings.log_filters.ProductionFilter',
        },
        'error_log_filter': {
            '()': 'pr_settings.log_filters.ErrorLogFilter',
        },
        'security_log_filter': {
            '()': 'pr_settings.log_filters.SecurityLogFilter',
        },
    },

    # Форматтеры
    'formatters': {
        'general': {
            'format': '{asctime} | {levelname} | {module} | {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'errors': {
            'format': '{asctime} | {levelname} | {message} | {pathname}\n{exc_info}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'security': {
            'format': '{asctime} | {levelname} | {module} | {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'email': {
            'format': '{asctime} | {levelname} | {message} | {pathname}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },

    # 👇 ОБРАБОТЧИКИ
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'pr_settings.log_handlers.LevelBasedConsoleHandler',  # из шага 4
            'filters': ['debug_only'],
        },
        'general_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'general.log'),
            'maxBytes': 10485760,
            'backupCount': 5,
            'formatter': 'general',
            'filters': ['production_only'],
        },
        'errors_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'errors.log'),
            'maxBytes': 10485760,
            'backupCount': 5,
            'formatter': 'errors',
            'filters': ['error_log_filter'],
        },
        'security_file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'security.log'),
            'maxBytes': 10485760,
            'backupCount': 5,
            'formatter': 'security',
            'filters': ['security_log_filter'],
        },
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
            'formatter': 'email',
            'filters': ['production_only'],
        },
    },

    # Файл general.log
    'general_file': {
        'level': 'INFO',
        'class': 'logging.handlers.RotatingFileHandler',
        'filename': os.path.join(LOG_DIR, 'general.log'),
        'maxBytes': 10485760,
        'backupCount': 5,
        'formatter': 'general',
        'filters': ['production_only'],  # только при DEBUG=False
    },

    # Файл errors.log
    'errors_file': {
        'level': 'ERROR',
        'class': 'logging.handlers.RotatingFileHandler',
        'filename': os.path.join(LOG_DIR, 'errors.log'),
        'maxBytes': 10485760,
        'backupCount': 5,
        'formatter': 'errors',
        'filters': ['error_log_filter'],
    },

    # Файл security.log
    'security_file': {
        'level': 'DEBUG',
        'class': 'logging.handlers.RotatingFileHandler',
        'filename': os.path.join(LOG_DIR, 'security.log'),
        'maxBytes': 10485760,
        'backupCount': 5,
        'formatter': 'security',
        'filters': ['security_log_filter'],
    },

    # Email
    'mail_admins': {
        'level': 'ERROR',
        'class': 'django.utils.log.AdminEmailHandler',
        'formatter': 'email',
        'filters': ['production_only'],
    },

    # Логгеры
    'loggers':{
        'django': {
            'handlers': ['console', 'general_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['errors_file', 'mail_admins'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.server': {
            'handlers': ['errors_file', 'mail_admins'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.template': {
            'handlers': ['errors_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['errors_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['security_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'allauth': {
            'level': 'DEBUG',
            'handlers': ['console'],
            'propagate': False,
        },
        'allauth.socialaccount': {
            'level': 'DEBUG',
            'handlers': ['console'],
            'propagate': False,
        },
    },
}

